# Generated by Django 2.2.16 on 2022-12-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221225_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created',
        ),
    ]
